openapi: 3.0.1
info:
  title: Rock Paper Scissor goesbrrr
  description: Rock Paper Scissor dashboard api
  contact:
    email: mikelrisyad@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: http://localhost:3000/v1
tags:
- name: player
  description: player api
- name: game
  description: game api
paths:
  /player:
    get:
      tags:
      - player
      summary: Get All Players
      description: Get All Data Players
      operationId: getPlayers
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        "404":
          description: Not Found
          content: {}
      security:
      - player_auth:
        - write:player
        - read:player
      - api_key: []
      x-swagger-router-controller: Player
  /player/:id:
    get:
      tags:
      - player
      summary: get player id
      operationId: playeridGET
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        "404":
          description: Not Found
          content: {}
      security:
      - player_auth:
        - write:player
        - read:player
      - api_key: []
      x-swagger-router-controller: Player
    put:
      tags:
      - player
      summary: update player id
      description: update spesific player
      operationId: playeridPUT
      requestBody:
        description: user object that needs to be added to the biodata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        "404":
          description: Not Found
          content: {}
      security:
      - player_auth:
        - write:player
        - read:player
      x-swagger-router-controller: Player
    post:
      tags:
      - player
      summary: insert player data
      operationId: playeridPOST
      requestBody:
        description: user object that needs to be added to the biodata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
        required: true
      responses:
        "200":
          description: success
          content: {}
      security:
      - player_auth:
        - write:player
        - read:player
      x-swagger-router-controller: Player
    delete:
      tags:
      - player
      summary: delete player on spesific id
      operationId: playeridDELETE
      responses:
        "200":
          description: success
          content: {}
        "404":
          description: Not Found
          content: {}
      security:
      - player_auth:
        - write:player
        - read:player
      x-swagger-router-controller: Player
  /game/history:
    get:
      tags:
      - game
      summary: get all game history
      operationId: gameHistoryGET
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponses'
        "404":
          description: No game history Found
          content: {}
      security:
      - player_auth:
        - write:player
        - read:player
      x-swagger-router-controller: Game
  /game/history/:id:
    get:
      tags:
      - game
      summary: get game history on a player
      operationId: gameHistoryidGET
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponses'
        "404":
          description: No game history Found
          content: {}
      security:
      - player_auth:
        - write:player
        - read:player
      x-swagger-router-controller: Game
components:
  schemas:
    Player:
      required:
      - email
      - password
      - username
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
          example: mikael
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          example: mikelrisyad@gamil.com
        password:
          type: string
          example: "123456"
        phone:
          type: string
        avatarUrl:
          type: string
      example:
        firstName: firstName
        lastName: lastName
        password: "123456"
        phone: phone
        avatarUrl: avatarUrl
        id: 0
        email: mikelrisyad@gamil.com
        username: mikael
    GameResponses:
      type: object
      properties:
        history:
          type: array
          items:
            $ref: '#/components/schemas/GameHistory'
        username:
          type: string
        playerPoint:
          type: string
      example:
        playerPoint: playerPoint
        history:
        - winCount: 0.80082819046101150206595775671303272247314453125
          gameCount: 6.02745618307040320615897144307382404804229736328125
        - winCount: 0.80082819046101150206595775671303272247314453125
          gameCount: 6.02745618307040320615897144307382404804229736328125
        username: username
    GameHistory:
      type: object
      properties:
        winCount:
          type: number
        gameCount:
          type: number
      example:
        winCount: 0.80082819046101150206595775671303272247314453125
        gameCount: 6.02745618307040320615897144307382404804229736328125
  securitySchemes:
    player_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:player: modify user biodata
            read:player: read user biodata
    api_key:
      type: apiKey
      name: api_key
      in: header
